### ISSUE TITLE
Breaks on complex multiline strings in YAML

### ISSUE THREAD

**Issue by farski** [aws-cloudformation/aws-cfn-lint-visual-studio-code#8]
For YAML templates with inline Lambda function code (eg [this](https://github.com/PRX/Infrastructure/blob/master/etc/adzerk-poller.yml) or [this](https://github.com/PRX/Infrastructure/blob/master/etc/workable-poller.yml)), the extension breaks on certain strings, even when the linter has no issues on the command line.

For example, [this line](https://github.com/PRX/Infrastructure/blob/master/etc/workable-poller.yml#L107) seems to trip it up in VSC causing `SyntaxError: Unexpected end of JSON input` and `Connection to server got closed. Server will not be restarted.`

Even if that line is commented out in the YAML it fails (though I can't say for sure YAML supports comment lines in the middle of a string block). The only way to get it to work is to remove the line from the file.

**Comment by kddejong** [comment]
thanks @farski let me look at this and see what I can find.

**Comment by kddejong** [comment]
I was able to replicate this error when using Python 2.7 for cfn-lint.  Fix above.  For Python 3 things seem to work without issue.

This was the error I saw using Python 2.7.
```
File "/Library/Python/2.7/site-packages/yaml/constructor.py", line 88, in construct_object
    data = constructor(self, node)
  File "/Users/kddejong/code/python/cfn-python-lint/src/cfnlint/cfn_yaml.py", line 115, in construct_yaml_str
    assert isinstance(obj, str)
```

**Comment by kddejong** [comment]
@farski can you confirm things are working with the newest release?  From what I can tell you must have been using Python 2 with Visual Studio which we have now fixed with the latest release of cfn-lint but I want to make sure I have that right.

**Comment by farski** [comment]
I think I'm still seeing the problem. Full log dump [here](https://gist.github.com/farski/ae29e30829731f0eaba32461c9708a61).

**Comment by kddejong** [comment]
ok.  I was able to replicate the issue (originally) in 2.7 but not in 3.6.  After the most recent fix for 0.2.2 of cfn-lint we should have had this fixed for both Python versions. I'll dig a little deeper and find a way to get this replicated.

**Comment by farski** [comment]
If there's anything else I can do to help let me know. Python isn't my strongest, so for debugging environment-related stuff or the code itself I'd need some support, but I'm willing to help.

**Comment by miparnisari** [comment]
@farski @kddejong 

I just tried to reproduce this on Windows with Python 2.7 & 3.6, `cfn-lint` 0.29.0 and [this](https://github.com/PRX/Infrastructure/blob/master/etc/workable-poller.yml) template. I got 0 errors.

**Comment by farski** [comment]
@miparnisari That template also appears to be working fine for me now. No errors, and it does correctly catch issues if I introduce them, so the linter is working as expected.

I can't remember the last time I ran into this issue, so I'm thinking it's been resolved.
